import './globals.css'

export const metadata = {
  title: 'Your App Name',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>Header Here</header>
        <main>{children}</main>
        <footer>Footer Here</footer>
      </body>
    </html>
  )
}
